name: Run TikTok Selenium Script

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.12"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium undetected-chromedriver python-dotenv tiktok-captcha-solver requests

    - name: Install Google Chrome
      run: |
        wget https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.87/linux64/chrome-linux64.zip
        unzip chrome-linux64.zip
        sudo mv chrome-linux64 /usr/local/bin/chrome
        if [ -L /usr/bin/google-chrome ]; then
          sudo rm /usr/bin/google-chrome
        fi
        sudo ln -s /usr/local/bin/chrome/chrome /usr/bin/google-chrome

    - name: Run TikTok Automation Script
      env:
        TIKTOK_EMAIL: ${{ secrets.TIKTOK_EMAIL }}
        TIKTOK_PASSWORD: ${{ secrets.TIKTOK_PASSWORD }}
        CAPTCHA_KEY: ${{ secrets.CAPTCHA_KEY }}
      run: |
        python tiktok.py
